all:
  hosts:
    worker3.sciencedata.dk:
    worker4.sciencedata.dk:
    worker5.sciencedata.dk:
  children:
    cluster:
      hosts:
        worker3.sciencedata.dk:
        worker4.sciencedata.dk:
        worker5.sciencedata.dk:
    control_plane:
      hosts:
        worker3.sciencedata.dk:
    worker_nodes:
      hosts:
        worker4.sciencedata.dk:
        worker5.sciencedata.dk:
