all:
  hosts:
    worker3.sciencedata.dk:
      trusted_network_address: "10.0.0.131"
      public_network_address: "130.226.137.135"
      trusted_network_interface: "enp6s4f1"
      public_network_interface: "enp0s9"
    worker5.sciencedata.dk:
      trusted_network_address: "10.0.0.129"
      trusted_network_interface: "enp6s4f1"
  children:
    cluster:
      hosts:
        worker3.sciencedata.dk:
        worker5.sciencedata.dk:
    control_plane:
      hosts:
        worker5.sciencedata.dk:
    worker_nodes:
      hosts:
        worker3.sciencedata.dk:
