all:
  hosts:
    worker3.sciencedata.dk:
      control_plane: True
    worker4.sciencedata.dk:
      control_plane: False
    worker5.sciencedata.dk:
      control_plane: False
  children:
    cluster:
      hosts:
        worker3.sciencedata.dk:
        worker4.sciencedata.dk:
        worker5.sciencedata.dk:
