all:
  hosts:
    worker3.sciencedata.dk:
      trusted_network_address: "10.0.0.131"
    worker5.sciencedata.dk:
      trusted_network_address: "10.0.0.129"
  children:
    cluster:
      hosts:
        worker3.sciencedata.dk:
        worker5.sciencedata.dk:
    control_plane:
      hosts:
        worker3.sciencedata.dk:
    worker_nodes:
      hosts:
        worker5.sciencedata.dk:
