- name: Check calico installed
  when: "'control_plane' in group_names"
  ansible.builtin.shell: kubectl calico version | grep "Cluster Version"
  failed_when: False
  changed_when: False
  register: calico_result

  # If there are no lines of stdout from the command above, then calico isn't installed and needs to be now.
- name: Install Calico in control_plane
  when:
    - "'control_plane' in group_names"
    - calico_result.stdout_lines | count == 0
  block:
      # helm repo add projectcalico https://...
    - name: Install calico, add helm repo (1/5)
      kubernetes.core.helm_repository:
        name: projectcalico
        repo_url: "https://projectcalico.docs.tigera.io/charts"

    - name: Install calico, copy values (2/5)
      ansible.builtin.template:
        src: "{{ playbook_dir }}/install/templates/calico_helm_values.yaml.j2"
        dest: /etc/kubernetes/helm_values/calico.yaml
        owner: root
        group: root
        mode: 0640

      # helm install -f /etc/kubernetes/helm_values/calico.yaml calico projectcalico/tigera-operator
      # --namespace tigera-operator --create-namespace
      # and then wait
    - name: Install calico, install chart (3/5)
      kubernetes.core.helm:
        update_repo_cache: True
        release_name: calico
        release_namespace: tigera-operator
        create_namespace: True
        chart_ref: projectcalico/tigera-operator
        atomic: True
        chart_version: "{{ calico_version }}"
        values_files:
          - /etc/kubernetes/helm_values/calico.yaml
        wait: True

      # curl && sha256sum
    - name: Install Calico, fetch calicoctl (4/5)
      ansible.builtin.get_url:
        url: "{{ calicoctl_url }}"
        checksum: "{{ calicoctl_checksum }}"
        dest: /usr/local/bin/kubectl-calico
        mode: 0751
        owner: root
        group: root

    - name: Install Calico, sleep before continuing to install worker nodes to ensure all Calico components are running (5/5)
      # There are calico-apiserver and calico-system components that are indirectly created by the tigera-operator pod,
      # so the helm command doesn't wait for them to reach ready state.
      ansible.builtin.shell: sleep 45
