- name: Install user pods backend
  when: "'control_plane' in group_names"
  block:
    - name: Install user pods backend, copy manifest (1/2)
      ansible.builtin.template:
        src: "{{ playbook_dir }}/install/templates/user_pods_backend.yaml.j2"
        dest: /etc/kubernetes/custom_manifests/user_pods_backend.yaml
        owner: root
        group: root
        mode: 0640

    - name: Install user pods backend, apply manifest (2/2)
      kubernetes.core.k8s:
        kubeconfig: "{{ k8s_admin_config }}"
        apply: True
        src: /etc/kubernetes/custom_manifests/user_pods_backend.yaml
        wait: True
