- name: Get list of joined worker nodes (1/2)
  when: "'control_plane' in group_names"
  ansible.builtin.shell: kubectl get nodes | tail -n +2 | awk '{print $1;}'
  changed_when: False
  register: print_nodes

  # Create an ansible variable that is a list of hostnames of the worker nodes that are joined
- name: Get list of joined worker nodes (2/2)
  when: "'control_plane' in group_names"
  ansible.builtin.set_fact:
    nodes_that_are_joined: "{{ print_nodes.stdout_lines }}"


  # Create an ansible variable that is a list of all the hostnames of the hosts in the 'worker_nodes' group.
  # Not the hostname reached by ssh, but the hostname the host itself knows and uses inside the cluster.
- name: Get list of nodes that should be joined
  ansible.builtin.set_fact:
    nodes_that_should_be_joined: "{{ hostvars | dict2items |
    selectattr('key', 'in', groups['worker_nodes']) |
    map(attribute='value') | map(attribute='ansible_hostname') }}"

  # Create an ansible variable with the list of nodes that should be joined minus the nodes that already are
- name: Get list of nodes that should be joined but are not yet
  when: "'control_plane' in group_names"
  ansible.builtin.set_fact:
    nodes_not_joined: "{{ nodes_that_should_be_joined |
    reject('in', nodes_that_are_joined) }}"

  # If there is at least one worker node that needs to join
- name: Get tokens for nodes to join
  when:
    - "'control_plane' in group_names"
    - nodes_not_joined | count > 0
  block:
      # Create a token and save the output as an ansible variable
    - name: Get tokens for nodes to join, create token (1/2)
      ansible.builtin.shell: kubeadm token create
      register: token_create

      # Get the hash of the control plane CA certificate and save the output as an ansible variable
    - name: Get tokens for nodes to join, get ca-cert-hash (2/2)
      ansible.builtin.shell: >
        openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt |
        openssl rsa -pubin -outform der 2>/dev/null |
        openssl dgst -sha256 -hex | sed 's/^.* //'
      register: ca_cert_hash
      changed_when: False

  # The `when` clause makes this step only run on hosts which are in the list of nodes_not_joined
- name: Join all missing nodes
  when: ansible_hostname in hostvars[groups['control_plane'][0]]['nodes_not_joined']
  ansible.builtin.shell:
    cmd: |
      kubeadm join --token \
      {{ hostvars[groups['control_plane'][0]]['token_create']['stdout'] }} \
      {{ hostvars[groups['control_plane'][0]]['trusted_network_address'] }}:\
      {{ apiserver_port }} \
      --discovery-token-ca-cert-hash sha256:\
      {{ hostvars[groups['control_plane'][0]]['ca_cert_hash']['stdout'] }} \
      2> /var/log/kubeadm_join_error.txt \
      > /var/log/kubeadm_join_output.txt

- name: If no worker nodes, annotate the control plane node to allow it to schedule pods
  when: groups['worker_nodes'] | count == 0
  ansible.builtin.shell:
    cmd: kubectl taint nodes --all node-role.kubernetes.io/control-plane-

# By default, a control plane has a control-plane=NoSchedule taint, which prevents pods from being
# scheduled on it. This replaces that taint with control-plane=PreferNoSchedule,
# which means that if there is another node available, a new pod will be scheduled elsewhere, but if
# the control plane is the only one, it can be scheduled there without specifying in the pod's manifest.
# https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
- name: If there are worker nodes, re-annotate the control plane with a soft taint
  when:
    - groups['worker_nodes'] | count > 0
    - "'control_plane' in group_names"
  ansible.builtin.shell: |
    kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/control-plane:NoSchedule-
    kubectl taint nodes {{ ansible_hostname }} --overwrite node-role.kubernetes.io/control-plane:PreferNoSchedule



  # Finally check that there are no nodes left unjoined
- name: Get list of joined worker nodes after worker_init (1/2)
  delegate_to: "{{ groups['control_plane'][0] }}"
  ansible.builtin.shell: kubectl get nodes | tail -n +2 | awk '{print $1;}'
  changed_when: False
  register: print_nodes

- name: Get list of joined worker nodes after worker_init (2/2)
  ansible.builtin.set_fact:
    nodes_that_are_joined: "{{ print_nodes.stdout_lines }}"


- name: Get list of nodes that should be joined but are not after worker_init should be completed
  ansible.builtin.set_fact:
    nodes_not_joined: "{{ nodes_that_should_be_joined |
    reject('in', nodes_that_are_joined) }}"

- name: Fail if nodes are left unjoined
  debug:
    msg: "Nodes left unjoined (should be empty): {{ nodes_not_joined }}"
  failed_when: nodes_not_joined | count > 0

