# Kubernetes
pod_network_cidr: "10.2.0.0/16"
trusted_network_cidr: "10.0.0.0/16"
kubernetes_major_version: "1"
kubernetes_minor_version: "25"
kubernetes_patch_version: "2"
kubernetes_version: "{{ kubernetes_major_version }}.{{ kubernetes_minor_version }}.{{ kubernetes_patch_version }}"
k8s_admin_config: "/etc/kubernetes/admin.conf"
k8s_admin_context: "/kubernetes-admin@kubernetes"
apiserver_port: "6443"

# Cri-o (Container Runtime Interface)
crio_os_tag: "xUbuntu_22.04"
crio_version: "{{ kubernetes_major_version }}.{{ kubernetes_minor_version }}.1"
crictl_version: "v{{ kubernetes_major_version }}.{{ kubernetes_minor_version }}.0"
crictl_url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-amd64.tar.gz"
crictl_checksum: "sha256:86ab210c007f521ac4cdcbcf0ae3fb2e10923e65f16de83e0e1db191a07f0235"

# Golang
golang_version: "1.19.1"
golang_tar_url: "https://go.dev/dl/go1.19.1.linux-amd64.tar.gz"
golang_tar_checksum: "sha256:acc512fbab4f716a8f97a8b3fbaa9ddd39606a28be6c2515ef7c6c6311acffde"

# Helm
helm_binary_url: "https://get.helm.sh/helm-v3.10.1-linux-amd64.tar.gz"
helm_binary_checksum: "sha256:c12d2cd638f2d066fec123d0bd7f010f32c643afdf288d39a4610b1f9cb32af3"
helm_version: "3.10.1"

# Calico (Container Network Interface)
calicoctl_url: "https://github.com/projectcalico/calico/releases/download/v3.24.1/calicoctl-linux-amd64"
calicoctl_checksum: "sha256:10a36ebc7a4cf355b28e061f5a5f4b261daff4773a51ac73ca1071e7551a934a"

# Cert_manager
letsencrypt_email: "joshuaclement@deic.dk"
