- name: Install commonly-used packages
  ansible.builtin.apt:
    update_cache: True
    name:
      - zsh
  become: True

- name: Update
  ansible.builtin.apt:
    update_cache: True
    upgrade: True
  become: True

- name: Copy zshrc for a nice command line experience
  ansible.builtin.copy:
    src: "{{ role_path }}/files/zshrc"
    dest: /home/user/.zshrc
    owner: user
    group: user
    mode: 0644

- name: Set user shell
  ansible.builtin.user:
    shell: /bin/zsh
    name: user
  become: True

- name: Install golang, fetch files (1/3)
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.19.1.linux-amd64.tar.gz
    checksum: sha256:acc512fbab4f716a8f97a8b3fbaa9ddd39606a28be6c2515ef7c6c6311acffde
    dest: /tmp/go.tar.gz

- name: Install golang, extract (2/3)
  ansible.builtin.unarchive:
    remote_src: True
    src: /tmp/go.tar.gz
    dest: /usr/local/
  become: True

- name: Install golang, clean (3/3)
  ansible.builtin.file:
    state: absent
    path: /tmp/go.tar.gz
