- name: Install Calico in control_plane
  tags:
    - k8sinstall
    - calico
  when: "'control_plane' in group_names"
  block:
    - name: Install Calico, get manifest (1/6)
      ansible.builtin.get_url:
        url: "{{ calico_manifest_url }}"
        dest: /tmp/tigera-operator.yaml
        checksum: "{{ calico_manifest_checksum }}"

    # Needs server_side_apply in order to avoid the annotations.last-applied-configuration too long error
    - name: Install Calico, apply manifest (2/6)
      kubernetes.core.k8s:
        kubeconfig: "{{ k8s_admin_config }}"
        apply: True
        src: /tmp/tigera-operator.yaml
        wait: True
        server_side_apply:
          field_manager: kubectl
          force_conflicts: True

    - name: Install Calico, copy config (3/6)
      ansible.builtin.template:
        src: "{{ role_path }}/templates/tigera-custom-resources.yml.j2"
        dest: /tmp/tigera-custom-resources.yaml

    - name: Install Calico, apply custom resource manifest (4/6)
      kubernetes.core.k8s:
        kubeconfig: "{{ k8s_admin_config }}"
        apply: True
        src: /tmp/tigera-custom-resources.yaml
        wait: True
        server_side_apply:
          field_manager: kubectl
          force_conflicts: True

    - name: Install Calico, clean up files (5/6)
      ansible.builtin.file:
        path: /tmp/tigera-custom-resources.yaml
        state: absent

    - name: Install Calico, clean up files (6/6)
      ansible.builtin.file:
        path: /tmp/tigera-operator.yaml
        state: absent

- name: Install calicoctl
  tags:
    - k8sinstall
    - calico
  block:
    - name: Install calicoctl, fetch
      ansible.builtin.get_url:
        url: "{{ calicoctl_url }}"
        checksum: "{{ calicoctl_checksum }}"
        dest: /usr/local/bin/kubectl-calico
        mode: 0751
        owner: root
        group: root
