- name: Check if control plane is initialized
  when: "'control_plane' in group_names"
  ansible.builtin.shell: kubectl get nodes
  failed_when: False
  changed_when: False
  register: kubectl_result

- name: Check if control_plane port {{ control_plane_apiserver_port }} is occupied
  when: "'control_plane' in group_names"
  ansible.builtin.shell: netstat -tlpn | grep ":{{ control_plane_apiserver_port }}"
  failed_when: False
  changed_when: False
  register: port_result

- name: Initialize control plane
  when:
    - "'control_plane' in group_names"
    - kubectl_result.rc != 0
    - port_result.stdout_lines | count == 0
  block:
    - name: Initialize control plane, start kubelet (1/5)
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
        enabled: True
        daemon_reload: True

    - name: Initialize control plane, copy kubeadm config (2/5)
      ansible.builtin.template:
        src: "{{ role_path }}/templates/kubeadm-config.yml.j2"
        dest: /etc/kubernetes/kubeadm-config.yml
        owner: root
        group: root
        mode: 0644

    - name: Initialize control plane, initialize kubeadm (3/5)
      ansible.builtin.shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yml 2>&1 > /var/log/kubeadm_init_output.txt

    - name: Initialize control plane, make config dirs (4/5)
      loop:
        - username: "user"
          homepath: "/home/user"
        - username: "root"
          homepath: "/root"
      ansible.builtin.file:
        path: "{{ item.homepath }}/.kube"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        state: directory

    - name: Initialize control plane, copy kubectl config (5/5)
      loop:
        - username: "user"
          homepath: "/home/user"
        - username: "root"
          homepath: "/root"
      ansible.builtin.copy:
        dest: "{{ item.homepath }}/.kube/config"
        src: /etc/kubernetes/admin.conf
        remote_src: True
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: 0600
