- name: Prepare network prerequisites
  tags:
    - sysprepare
    - k8sinstall
  block:
  - name: Prepare network prerequisites, load modules br_netfilter (1/4)
    ansible.builtin.shell:
      cmd: modprobe br_netfilter && modprobe overlay

  - name: Prepare network prerequisites, set /etc/modules-load.d/k8s.conf (2/4)
    ansible.builtin.copy:
      src: "{{ role_path }}/files/modules-load-k8s.conf"
      dest: /etc/modules-load.d/k8s.conf
      owner: root
      group: root
      mode: 0644

  - name: Prepare network prerequisites, set /etc/sysctl.d/k8s.conf (3/4)
    ansible.builtin.copy:
      src: "{{ role_path }}/files/sysctl-k8s.conf"
      dest: /etc/sysctl.d/k8s.conf
      owner: root
      group: root
      mode: 0644

  - name: Prepare network prerequisites, reload sysctl configuration (4/4)
    ansible.builtin.shell:
      cmd: sysctl --system



- name: Check crictl version {{ crictl_version }} installed
  tags:
    - k8sinstall
    - crio
  ansible.builtin.shell: |
    VERSION=$(crictl --version | sed -e 's/.*\(v[0-9]\+[.][0-9]\+[.][0-9]\+\).*/\1/')
    [[ $VERSION != {{ crictl_version }} ]]
  register: crictl_correct_version
  ignore_errors: True
  
- name: Install crictl
  tags:
    - k8sinstall
    - crio
  when: crictl_correct_version == 0
  block:
  - name: Install crictl, fetch (1/3)
    ansible.builtin.get_url:
      url: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-amd64.tar.gz
      dest: /tmp/crictl.tar.gz

  - name: Install crictl, extract (2/3)
    ansible.builtin.unarchive:
      remote_src: True
      src: /tmp/crictl.tar.gz
      dest: /usr/local/bin/

  - name: Install crictl, clean (3/3)
    ansible.builtin.file:
      state: absent
      path: /tmp/crictl.tar.gz

- name: Check cri-o is installed and running with the correct version
  ansible.builtin.shell: |
    VERSION=$(sudo crictl --runtime-endpoint unix:///var/run/crio/crio.sock version)
    [[ "$VERSION" != {{ crio_version }} ]]
  register: crio_installed
  ignore_errors: True
  tags:
    - k8sinstall
    - crio

- name: Install cri-o from repository
  tags:
    - k8sinstall
    - crio
  when: crio_installed == 0
  block:
  - name: Install cri-o from repository, add sources (1/5)
    ansible.builtin.template:
      src: "{{ role_path }}/templates/crio-sources.list.j2"
      dest: /etc/apt/sources.list.d/crio-sources.list
      owner: root
      group: root
      mode: 0644

  - name: Install cri-o from repository, get keys (2/5)
    ansible.builtin.uri:
      url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_os_tag }}/Release.key
      follow_redirects: safe
      dest: /tmp/libcontainers-key

  - name: Install cri-o from repository, get keys (3/5)
    ansible.builtin.uri:
      url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ kubernetes_minor_version }}/{{ crio_os_tag }}/Release.key
      follow_redirects: safe
      dest: /tmp/crio-key

  - name: Install cri-o from repository, install keys (4/5)
    ansible.builtin.shell: |
      cat /tmp/libcontainers-key | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg --yes
      cat /tmp/crio-key | gpg --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg --yes
      rm /tmp/libcontainers-key /tmp/crio-key

  - name: Install cri-o from repository, apt install (5/5)
    ansible.builtin.apt:
      update_cache: True
      name:
        - cri-o
        - cri-o-runc
        - containernetworking-plugins

  - name: Install cri-o from repository, copy crio config file
    ansible.builtin.copy:
      src: "{{ role_path }}/files/crio.conf"
      dest: /etc/crio/crio.conf
      owner: root
      group: root
      mode: 0644

  - name: Start and enable cri-o
    ansible.builtin.systemd:
      name: crio
      state: restarted
      enabled: True
      daemon_reload: True
