- name: Check kubelet version
  ansible.builtin.shell: kubelet --version | sed 's/.*v\([0-9]\+[.][0-9]\+[.][0-9]\+\).*/\1/'
  failed_when: False
  changed_when: False
  register: kubelet_version

- name: Check kubeadm version
  ansible.builtin.shell: kubeadm version | sed 's/.*GitVersion:\"v\([0-9]\+[.][0-9]\+[.][0-9]\+\).*/\1/'
  failed_when: False
  changed_when: False
  register: kubeadm_version

- name: Check kubectl version
  ansible.builtin.shell: kubectl version --short | grep "Client Version" | sed 's/.*v\([0-9]\+[.][0-9]\+[.][0-9]\+\)/\1/'
  failed_when: False
  changed_when: False
  register: kubectl_version

- name: Install kubernetes bootstrapping parts
  when:
    - kubelet_version.stdout != kubernetes_version
    - kubeadm_version.stdout != kubernetes_version
    - kubectl_version.stdout != kubernetes_version
  block:
    - name: Install kubernetes bootstrapping parts, get signing key (1/6)
      ansible.builtin.get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
      
    - name: Install kubernetes bootstrapping parts, add sources (2/6)
      ansible.builtin.copy:
        src: "{{ role_path }}/files/kubernetes.list"
        dest: /etc/apt/sources.list.d/kubernetes.list
        owner: root
        group: root
        mode: 0644

    - name: Install kubernetes bootstrapping parts, install packages (3/6)
      ansible.builtin.apt:
        update_cache: True
        name:
          - kubelet={{ kubernetes_version }}-00
          - kubeadm={{ kubernetes_version }}-00
          - kubectl={{ kubernetes_version }}-00
        state: present

    - name: Install kubernetes bootstrapping parts, hold package version constant (4/6)
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: hold

    - name: Install kubernetes bootstrapping parts, hold package version constant (5/6)
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Install kubernetes bootstrapping parts, hold package version constant (6/6)
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: hold
