- name: Install kubernetes bootstrapping parts
  tags:
    - k8sinstall
  block:
    - name: Install kubernetes bootstrapping parts, get signing key (1/6)
      ansible.builtin.get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
      
    - name: Install kubernetes bootstrapping parts, add sources (2/6)
      ansible.builtin.copy:
        src: "{{ role_path }}/files/kubernetes.list"
        dest: /etc/apt/sources.list.d/kubernetes.list
        owner: root
        group: root
        mode: 0644

    - name: Install kubernetes bootstrapping parts, install packages (3/6)
      ansible.builtin.apt:
        update_cache: True
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Install kubernetes bootstrapping parts, hold package version constant (4/6)
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: hold

    - name: Install kubernetes bootstrapping parts, hold package version constant (5/6)
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Install kubernetes bootstrapping parts, hold package version constant (6/6)
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: hold

