- name: Disable swap
  tags:
    - swap
  block:

  ### If swap is on, then `swapon --show` will output the swap devices in a table
  ### started with NAME. The grep command will have a nonzero exit code if it doesn't
  ### get that table.
  - name: Check if swap enabled
    ansible.builtin.shell:
      cmd: swapon --show | grep NAME
    register: swap_enabled
    failed_when: False
    changed_when: False
  
  - name: Disable swap since kubernetes can't work with swap enabled (1/2)
    ansible.builtin.shell:
      cmd: swapoff -a
    when: swap_enabled == 0
  
  - name: Disable swap in fstab since kubernetes can't work with swap enabled (2/2)
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
    when: swap_enabled == 0


- name: Install/update system packages
  tags:
    - sysupdate
  block:
  - name: Make sure packages are installed
    ansible.builtin.apt:
      update_cache: True
      name:
        - python3-pip
        - zsh
        - net-tools
        - iptables-persistent
      state: present
  
  - name: Update
    ansible.builtin.apt:
      update_cache: True
      upgrade: True

  - name: Check restart needed
    ansible.builtin.shell: "[[ -f /var/run/reboot-required ]]"
    failed_when: False
    changed_when: False
    register: reboot_required

  - name: Notify restart needed
    ansible.builtin.debug:
      msg: "***Reboot is required***"
    when: reboot_required.rc == 0

- name: Setup shell
  tags:
    - shell
  block:
  - name: Copy zshrc for a nice command line experience
    loop:
      - username: "user"
        homepath: "/home/user"
      - username: "root"
        homepath: "/root"
    ansible.builtin.copy:
      src: "{{ role_path }}/files/zshrc"
      dest: "{{ item.homepath }}/.zshrc"
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
      mode: 0644
  
  - name: Set user shell
    loop:
      - "user"
      - "root"
    ansible.builtin.user:
      shell: /bin/zsh
      name: "{{ item }}"

- name: Install python dependencies for ansible modules
  tags:
    - python
  block:
    - name: Install kubernetes module
      pip:
        name: kubernetes

- name: Set firewall rules
  tags:
    - firewall
  block:
    - name: Set firewall rules, copy persistent files (1/2)
      ansible.builtin.copy:
        src: "{{ role_path }}/files/rules.v4"
        dest: "/etc/iptables/rules.v4"
        owner: root
        group: root
        mode: 0644
      register: copied_firewall_rules

    - name: Set firewall rules, flush and reload rules (2/2)
      when: copied_firewall_rules.changed
      ansible.builtin.shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X && iptables-restore < /etc/iptables/rules.v4
