- name: Install user pods backend
  when: "'control_plane' in group_names"
  block:
    - name: Install user pods backend, copy persistent volume manifest (1/8)
      ansible.builtin.template:
        src: "{{ backend_manifests_dir }}/read_only_PVs.yaml.j2"
        dest: /etc/kubernetes/custom_manifests/read_only_PVs.yaml
        owner: root
        group: root
        mode: 0640

    - name: Install user pods backend, apply persistent volume manifest (2/8)
      kubernetes.core.k8s:
        kubeconfig: "{{ k8s_admin_config }}"
        apply: True
        src: /etc/kubernetes/custom_manifests/read_only_PVs.yaml
        wait: True

    - name: Install user pods backend, copy ingress dependency manifest (3/8)
      ansible.builtin.template:
        src: "{{ backend_manifests_dir }}/ingress_dependencies.yaml.j2"
        dest: /etc/kubernetes/custom_manifests/ingress_dependencies.yaml
        owner: root
        group: root
        mode: 0640

    - name: Install user pods backend, apply ingress dependency manifest (4/8)
      kubernetes.core.k8s:
        kubeconfig: "{{ k8s_admin_config }}"
        apply: True
        src: /etc/kubernetes/custom_manifests/ingress_dependencies.yaml
        wait: True

    - name: Install user pods backend, copy user pods backend manifest (5/8)
      ansible.builtin.template:
        src: "{{ backend_manifests_dir }}/deploy_user_pods_backend.yaml.j2"
        dest: /etc/kubernetes/custom_manifests/deploy_user_pods_backend.yaml
        owner: root
        group: root
        mode: 0640

    - name: Install user pods backend, apply user pods backend manifest (6/8)
      kubernetes.core.k8s:
        kubeconfig: "{{ k8s_admin_config }}"
        apply: True
        src: /etc/kubernetes/custom_manifests/deploy_user_pods_backend.yaml
        wait: True


    - name: Install user pods backend, copy testing manifest (7/8)
      ansible.builtin.template:
        src: "{{ backend_manifests_dir }}/deploy_user_pods_backend_testing.yaml.j2"
        dest: /etc/kubernetes/custom_manifests/deploy_user_pods_backend_testing.yaml
        owner: root
        group: root
        mode: 0640

    - name: Install user pods backend, apply testing manifest (8/8)
      kubernetes.core.k8s:
        kubeconfig: "{{ k8s_admin_config }}"
        apply: True
        src: /etc/kubernetes/custom_manifests/deploy_user_pods_backend_testing.yaml
        wait: True
