- name: Join worker nodes to the cluster
  tags:
    - worker_nodes
    - k8sinstall
  block:
    - name: Join worker nodes to the cluster, create token (1/3)
      ansible.builtin.shell: kubeadm token create
      register: token_create
      when: "'control_plane' in group_names"

    - name: Join worker nodes to the cluster, get ca-cert-hash (2/3)
      ansible.builtin.shell:
        cmd: >
          openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt |
          openssl rsa -pubin -outform der 2>/dev/null |
          openssl dgst -sha256 -hex | sed 's/^.* //'
      register: ca_cert_hash
      changed_when: False
      when: "'control_plane' in group_names"

    - name: Join worker nodes to the cluster, join (3/3)
      ansible.builtin.shell:
        cmd: |
          kubeadm join --token \
          {{ hostvars[groups['control_plane'][0]]['token_create']['stdout'] }} \
          {{ hostvars[groups['control_plane'][0]]['trusted_network_address'] }}:\
          {{ control_plane_apiserver_port }} \
          --discovery-token-ca-cert-hash sha256:\
          {{ hostvars[groups['control_plane'][0]]['ca_cert_hash']['stdout'] }}
      when: "'control_plane' not in group_names"
