- name: Clean all installed files
  block:
    - name: Clean all installed files, /etc/kubernetes (1/14)
      ansible.builtin.file:
        path: /etc/kubernetes
        state: absent

    - name: Clean all installed files, /home/user/.kube (2/14)
      ansible.builtin.file:
        path: /home/user/.kube
        state: absent

    - name: Clean all installed files, /root/.kube (3/14)
      ansible.builtin.file:
        path: /root/.kube
        state: absent

    - name: Clean all installed files, /etc/apt/sources.list.d/kubernetes.list (4/14)
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent

    - name: Clean all installed files, /etc/apt/sources.list.d/crio-sources.list (5/14)
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/crio-sources.list
        state: absent

    - name: Clean all installed files, /usr/share/keyrings/libcontainers-archive-keyring.gpg (6/14)
      ansible.builtin.file:
        path: /usr/share/keyrings/libcontainers-archive-keyring.gpg
        state: absent

    - name: Clean all installed files, /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg (7/14)
      ansible.builtin.file:
        path: /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg
        state: absent

    - name: Clean all installed files, /etc/modules-load.d/k8s.conf (8/14)
      ansible.builtin.file:
        path: /etc/crio/crio.conf
        state: absent

    - name: Clean all installed files, /etc/modules-load.d/k8s.conf (9/14)
      ansible.builtin.file:
        path: /etc/modules-load.d/k8s.conf
        state: absent

    - name: Clean all installed files, /etc/sysctl.d/k8s.conf (10/14)
      ansible.builtin.file:
        path: /etc/sysctl.d/k8s.conf
        state: absent

    - name: Clean all installed files, /usr/local/bin/crictl (11/14)
      ansible.builtin.file:
        path: /usr/local/bin/crictl
        state: absent

    - name: Clean all installed files, /usr/local/bin/kubectl-calico (12/14)
      ansible.builtin.file:
        path: /usr/local/bin/kubectl-calico
        state: absent

    - name: Clean all installed files, /home/user/.helm (13/14)
      ansible.builtin.file:
        path: /home/user/.helm
        state: absent

    - name: Clean all installed files, /usr/local/bin/helm (14/14)
      ansible.builtin.file:
        path: /usr/local/bin/helm
        state: absent
