- name: Reset firewall rules
  tags:
    - never
    - firewall
    - networking
  ansible.builtin.shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X && iptables-restore < /etc/iptables/rules.v4

- name: Reset vlan
  tags:
    - never
    - vlan
    - networking
  ansible.builtin.shell: |
    ip link delete {{ vlan_interface_name }}
